// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: 'AIzaSyD4gBeTPr2cD8pXa0cptuQTDxhy72XwzJY',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: 'AIzaSyD4gBeTPr2cD8pXa0cptuQTDxhy72XwzJY',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: 'AIzaSyD4gBeTPr2cD8pXa0cptuQTDxhy72XwzJY',
  );
  static const String _macosApiKey = String.fromEnvironment(
    'FIREBASE_MACOS_API_KEY',
    defaultValue: 'AIzaSyD4gBeTPr2cD8pXa0cptuQTDxhy72XwzJY',
  );
  static const String _windowsApiKey = String.fromEnvironment(
    'FIREBASE_WINDOWS_API_KEY',
    defaultValue: 'AIzaSyD4gBeTPr2cD8pXa0cptuQTDxhy72XwzJY',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:743080304620:web:11b60b09e44fa9f7ca2ac9',
    messagingSenderId: '743080304620',
    projectId: 'todolist-867ee',
    authDomain: 'todolist-867ee.firebaseapp.com',
    storageBucket: 'todolist-867ee.firebasestorage.app',
    measurementId: 'G-BXMS3QV7ZH',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:743080304620:android:8077a09f2ffe8aa0ca2ac9',
    messagingSenderId: '743080304620',
    projectId: 'todolist-867ee',
    storageBucket: 'todolist-867ee.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:743080304620:ios:b8099e5b5d16a6adca2ac9',
    messagingSenderId: '743080304620',
    projectId: 'todolist-867ee',
    storageBucket: 'todolist-867ee.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _macosApiKey,
    appId: '1:743080304620:ios:b8099e5b5d16a6adca2ac9',
    messagingSenderId: '743080304620',
    projectId: 'todolist-867ee',
    storageBucket: 'todolist-867ee.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: '1:743080304620:web:065f582726daa597ca2ac9',
    messagingSenderId: '743080304620',
    projectId: 'todolist-867ee',
    authDomain: 'todolist-867ee.firebaseapp.com',
    storageBucket: 'todolist-867ee.firebasestorage.app',
    measurementId: 'G-RPMMTP3CS1',
  );
}
